version: "3"
services:
  frontend:
    build:
      context: ./gui
      dockerfile: Dockerfile
    user: node
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./gui:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    tty: true
    networks:
      - mynetwork
    depends_on:
      - backend
    
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    user: python
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    tty: true
    
  extraction:
    build:
      context: ./extraction
      dockerfile: Dockerfile
    user: python
    volumes:
      - ./extraction:/app
    tty: true

networks:
  mynetwork:
    driver: bridge
